---

- name: 'Load vars.'
  include_tasks: 'vars.yml'

- name: 'Install os packages.'
  include_tasks: 'pkg.yml'
  when: 'ldr_pkg_enable'

- name: 'Install pips.'
  include_tasks: 'pip.yml'
  when: 'ldr_pip_enable'

- name: 'Apply roles.'
  include_tasks: 'role.yml'
  when: 'ldr_role_enable'
