---

- name: 'Load vars.'
  include_tasks: 'vars.yml'

- name: 'Install os packages.'
  include_tasks: 'package.yml'

- name: 'Install pips.'
  include_tasks: 'pip.yml'

- name: 'Apply roles.'
  include_role:
    name: '{{ _common_role }}'
  loop: '{{ common_os_roles
     |union(common_app_roles)
     |flatten|unique }}'
  loop_control:
    loop_var: '_common_role'
