---

- name: 'bootstrap required pips.'
  async: '{{ ldr_async_timeout }}'
  pip:
    name:
      - 'boto3'
      - 'botocore'
    state: 'present'
  poll: '{{ ldr_async_poll }}'

- name: 'Load ec2_metadata facts.'
  ec2_metadata_facts: {}
  delay: 1
  register: 'ec2_metadata_facts'
  retries: 3
  until: 'ec2_metadata_facts is not failed'
