---

- name: 'Set pip state.'
  include_tasks: 'pip_state.yml'
  loop: '{{ ldr_os_pips.keys()|union(ldr_app_pips.keys())|sort|unique }}'
  loop_control:
    loop_var: 'state'
  vars:
    name: '{{ ldr_os_pips[state]|default([])
       |union(ldr_app_pips[state]|default([]))
       |flatten|unique }}'
