---

- name: 'Set pip state.'
  include_tasks: 'pip_state.yml'
  loop: '{{ ldr_pips_os.keys()|union(ldr_pips.keys())|sort|unique }}'
  loop_control:
    loop_var: 'state'
  vars:
    name: '{{ ldr_pips_os[state]|default([])
       |union(ldr_pips[state]|default([]))
       |flatten|unique }}'
