---

- name: 'Include metadata.'
  include_tasks: 'meta.yml'

- name: 'Load ec2 tags.'
  ec2_tag:
    region: '{{ ansible_ec2_placement_region }}'
    resource: '{{ ansible_ec2_instance_id }}'
    state: 'list'
  delay: 1
  register: 'ldr_ec2'
  retries: 3
  until: 'ldr_ec2 is not failed'
