---

- name: 'Include metadata.'
  include_tasks: 'meta.yml'

- name: 'Load ec2 tags.'
  ec2_tag:
    region: '{{ ansible_ec2_placement_region }}'
    resource: '{{ ansible_ec2_instance_id }}'
    state: 'list'
  ignore_errors: true
  register: 'meta'
  when: 'meta|default(none) is not mapping'
