---

- name: 'Load tags.'
  include_tasks: 'tags.yml'

- name: 'Load app vars.'
  include_vars:
    depth: 1
    dir: '{{ playbook_dir }}/vars/{{ item }}'
    files_matching: '\.ya?ml$'
  failed_when: false
  ignore_errors: true
  loop:
    - 'os/{{ ldr_os1 }}'
    - 'os/{{ ldr_os2 }}'
    - 'os/{{ ldr_os3 }}'
    - 'os/{{ ldr_os4 }}'
    - 'os/{{ ldr_os5 }}'
    - 'all'
    - 'all/{{ env }}'
    - '{{ app }}'
    - '{{ app }}/{{ env }}'
  vars:
    app: '{{ ldr_app|default(ldr_ec2.tags.application
                       |default("default", true), true) }}'
    env: '{{ ldr_env|default(ldr_ec2.tags.environment
                       |default("default", true), true) }}'
