---

- name: 'Load tags.'
  include_tasks: 'tags.yml'

- name: 'Load app vars.'
  include_vars:
    depth: 1
    dir: '{{ playbook_dir }}/vars/{{ item }}'
    files_matching: '^.*\.yml$'
  failed_when: false
  ignore_errors: true
  loop:
    - 'all'
    - 'all/{{ env }}'
    - '{{ app }}'
    - '{{ app }}/{{ env }}'
    - 'os/{{ os1 }}'
    - 'os/{{ os2 }}'
    - 'os/{{ os3 }}'
    - 'os/{{ os4 }}'
    - 'os/{{ os5 }}'
  vars:
    app: '{{ common_app|default(meta.tags.application|default("default")) }}'
    env: '{{ common_env|default(meta.tags.environment|default("default")) }}'
    os1: '{{ ansible_system }}'
    os2: '{{ os1 }}.{{ ansible_os_family }}'
    os3: '{{ os2 }}.{{ ansible_distribution }}'
    os4: '{{ os3 }}.{{ ansible_distribution_major_version }}'
    os5: '{{ os3 }}.{{ ansible_distribution_version }}'
    
